import React from "react";
import { Link } from "wouter";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navbar />
      <main className="container mx-auto px-4 md:px-6 max-w-3xl pt-32 pb-24">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
        <p className="text-muted-foreground mb-10">Last updated: April 18, 2025</p>

        <div className="prose prose-slate max-w-none space-y-8 text-foreground">

          <section>
            <h2 className="text-2xl font-bold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using any website, application, WhatsApp bot, AI agent, or other digital product created or operated by Hovina ("we", "us", or "our"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">2. Description of Services</h2>
            <p className="text-muted-foreground leading-relaxed">
              Hovina provides technology services including but not limited to: website development, WhatsApp automation bots, AI agents, machine learning systems, custom software solutions, and system integrations. Services may be offered directly to end users or provided to businesses and their customers. Specific service terms may apply to individual products.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">3. User Responsibilities</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">By using our services, you agree to:</p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Provide accurate and truthful information when required</li>
              <li>Use our services only for lawful purposes</li>
              <li>Not attempt to gain unauthorised access to any part of our systems</li>
              <li>Not use our services to transmit spam, malware, or harmful content</li>
              <li>Not reverse engineer, decompile, or disassemble any of our software</li>
              <li>Comply with all applicable laws and regulations in your jurisdiction</li>
              <li>Respect the intellectual property rights of Hovina and third parties</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">4. WhatsApp and Messaging Services</h2>
            <p className="text-muted-foreground leading-relaxed">
              Our WhatsApp bots and messaging services operate in compliance with Meta's Terms of Service and WhatsApp's Business Policy. By interacting with any Hovina-operated WhatsApp bot, you acknowledge that your messages will be processed to provide the requested service. You must not use our bots to send unsolicited messages, engage in harassment, or violate any applicable laws. We reserve the right to block users who misuse our messaging services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">5. AI Services and Limitations</h2>
            <p className="text-muted-foreground leading-relaxed">
              Our AI agents and machine learning systems are provided as-is. Outputs generated by AI are not guaranteed to be accurate, complete, or suitable for any particular purpose. You should not rely solely on AI-generated content for critical decisions, including medical, legal, financial, or safety matters. Hovina is not liable for actions taken based on AI outputs.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">6. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              All content, software, designs, logos, and materials associated with Hovina's services are the intellectual property of Hovina or its licensors, protected by applicable copyright, trademark, and intellectual property laws. You may not reproduce, distribute, modify, or create derivative works without our express written permission. Custom software built for clients becomes the client's property upon full payment as agreed in a separate service agreement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">7. Privacy</h2>
            <p className="text-muted-foreground leading-relaxed">
              Your use of our services is also governed by our <Link href="/privacy" className="text-primary underline">Privacy Policy</Link>, which is incorporated into these Terms by reference. By using our services, you consent to the collection and use of information as described in our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">8. Disclaimer of Warranties</h2>
            <p className="text-muted-foreground leading-relaxed">
              Our services are provided on an "as is" and "as available" basis without any warranties of any kind, either express or implied. We do not warrant that our services will be uninterrupted, error-free, or completely secure. We disclaim all warranties including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">9. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              To the fullest extent permitted by applicable law, Hovina shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of or inability to use our services, even if we have been advised of the possibility of such damages. Our total liability to you for any claim arising from these terms shall not exceed the amount you paid us in the three months prior to the claim.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">10. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to suspend or terminate your access to any of our services at any time, with or without notice, for any reason including violation of these Terms. Upon termination, your right to use the service will immediately cease. Provisions that by their nature should survive termination shall remain in effect.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">11. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to modify these Terms at any time. We will indicate the date of the most recent update at the top of this page. Your continued use of our services after any changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">12. Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising under these Terms shall be resolved through good-faith negotiation, and if that fails, through binding arbitration or the courts of competent jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">13. Contact Us</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms of Service, please <Link href="/#contact" className="text-primary underline">contact us</Link> through our website.
            </p>
          </section>

        </div>
      </main>
      <Footer />
    </div>
  );
}
