kind = "web"
previewPath = "/"
title = "Suneldah"
version = "1.0.0"
id = "artifacts/suneldah"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24653

[services.development]
run = "pnpm --filter @workspace/suneldah run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/suneldah", "run", "build" ]
publicDir = "artifacts/suneldah/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24653"
BASE_PATH = "/"
